
-- Fix's issue First part where two of each boss is visble.
update creature set phaseid=378 where guid in (248315,248255,282942);

--add some fight flavor to mini boss's.
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry` IN(39141,39142,39143);

DELETE FROM `smart_scripts` where `entryorguid` IN(39141,39142,39143);

insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39141','0','0','0','4','0','100','0','0','0','0','0','11','79851','2','0','0','0','0','2','0','0','0','0','0','0','0','Commander Arrington - OnAggron - cast Fan of Kives.');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39141','0','1','0','0','0','100','0','1000','1000','50000','50000','11','60842','32','0','0','0','0','2','0','0','0','0','0','0','0','Commander Arrington - OnIC - cast Expose Armor.');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39141','0','2','0','0','0','100','0','2000','2000','4000','4000','11','79852','2','0','0','0','0','2','0','0','0','0','0','0','0','Commander Arrington - OnIC - cast Eviscerate.');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39141','0','3','0','0','0','100','0','4000','4000','50000','50000','11','60195','2','0','0','0','0','2','0','0','0','0','0','0','0','Commander Arrington - OnIC - cast Sinister Strike.');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39142','0','0','0','4','0','100','0','0','0','0','0','11','66060','2','0','0','0','0','1','0','0','0','0','0','0','0','Darkblade Cyn onaggro cast Sprint.');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39142','0','1','0','0','0','100','0','1000','1000','6000','6000','11','3583','32','0','0','0','0','2','0','0','0','0','0','0','0','Darkblade Cyn IC cast Deadly Poison.');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39142','0','2','0','0','0','100','0','2000','2000','4000','4000','11','60195','2','0','0','0','0','2','0','0','0','0','0','0','0','Darkblade Cyn IC cast Sinister Strike.');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39143','0','0','0','0','0','100','0','1000','1000','5000','5000','11','79866','2','0','0','0','0','2','0','0','0','0','0','0','0','Alexi  on agro. cast deadly throw ');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39143','0','1','2','4','0','100','0','0','0','0','0','11','79864','2','0','0','0','0','2','0','0','0','0','0','0','0','Alexi  on near. cast shadowstep.');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39143','0','2','0','61','0','100','0','0','0','0','0','11','79862','0','0','0','0','0','2','0','0','0','0','0','0','0','Alexi  OnLink. cast backstab.');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39143','0','3','0','0','0','100','0','1000','1000','2000','2000','11','79863','32','0','0','0','0','2','0','0','0','0','0','0','0','Alexi  InCombat. Hemorrhage.');

--Enable blizzlike fights to some Lost Isle's, Tranquil Coast npc's.

UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry` IN(39042,39044,39068,40785);

DELETE FROM `smart_scripts` where `entryorguid` IN(39042,39044,39068,40785);

insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39042','0','0','0','54','0','100','0','0','0','0','0','75','66657','0','0','0','0','0','1','0','0','0','0','0','0','0','Gnomeregan Paratrooper OnSummon add aura parachute .');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39042','0','1','0','1','0','100','0','2000','2000','2000','2000','69','1','0','0','0','0','0','8','0','0','0','1716.29','2876.75','9.1939','4.8564','Gnomeregan Paratrooper Link MoveInform >point. .');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39042','0','2','0','4','0','100','0','0','0','0','0','11','6660','2','0','0','0','0','2','0','0','0','0','0','0','0','Gnomeregan Paratrooper OnAggro Cast Shoot.');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39042','0','3','0','4','0','100','0','0','0','0','0','28','66657','0','0','0','0','0','1','0','0','0','0','0','0','0','Gnomeregan Paratrooper OnAggro Cast Shoot.');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39044','0','0','0','4','0','100','0','0','0','0','0','42','100','0','0','0','0','0','1','0','0','0','0','0','0','0','Orc Battlesworn onSpawn set invincibility level 15% health.');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39044','0','1','0','4','0','100','0','0','0','0','0','21','0','0','0','0','0','0','1','0','0','0','0','0','0','0','Orc Battlesworn onAggro stop combat movement.');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39044','0','2','0','7','0','100','0','0','0','0','0','21','1','0','0','0','0','0','1','0','0','0','0','0','0','0','Orc Battlesworn onEvade allow combat movement.');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39044','0','3','0','9','0','100','0','0','5','0','0','20','1','0','0','0','0','0','1','0','0','0','0','0','0','0','Orc Battlesworn Between 0-5 Range Start Auto Attack.');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39044','0','4','5','1','0','100','255','10000','10000','60000','60000','20','1','0','0','0','0','0','1','0','0','0','0','0','0','0','Orc Battlesworn onOOC allow combat movement.');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39044','0','5','0','61','0','100','0','0','0','0','0','78','0','0','0','0','0','0','1','0','0','0','0','0','0','0','Orc Battlesworn OnLink Script Reset.');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39068','0','0','1','1','0','100','1','0','0','0','0','21','0','0','0','0','0','0','1','0','0','0','0','0','0','0','Orc Scout - Out Of Combat - Disallow Combat Movement');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39068','0','1','0','61','0','100','0','0','0','0','0','20','0','0','0','0','0','0','1','0','0','0','0','0','0','0','Orc Scout - Out Of Combat - Stop Auto Attack');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39068','0','2','0','4','0','100','1','0','0','0','0','11','6660','0','0','0','0','0','2','0','0','0','0','0','0','0','Orc Scout - On Aggro - Cast 6660');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39068','0','3','4','9','0','100','0','5','30','2300','3900','11','6660','0','0','0','0','0','2','0','0','0','0','0','0','0','Orc Scout - Between 5-30 Range - Cast 6660');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39068','0','4','0','61','0','100','0','0','0','0','0','40','2','0','0','0','0','0','1','0','0','0','0','0','0','0','Orc Scout - Between 5-30 Range - Set Sheath Ranged');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39068','0','5','6','9','0','100','0','25','80','0','0','21','1','0','0','0','0','0','1','0','0','0','0','0','0','0','Orc Scout - Between 25-80 Range - Allow Combat Movement');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39068','0','6','0','61','0','100','0','0','0','0','0','20','1','0','0','0','0','0','1','0','0','0','0','0','0','0','Orc Scout - Between 25-80 Range - Start Auto Attack');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39068','0','7','8','9','0','100','0','0','5','0','0','21','1','0','0','0','0','0','1','0','0','0','0','0','0','0','Orc Scout - Between 0-5 Range - Allow Combat Movement');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39068','0','8','9','61','0','100','0','0','0','0','0','40','1','0','0','0','0','0','1','0','0','0','0','0','0','0','Orc Scout - Between 0-5 Range - Set Sheath Melee');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39068','0','9','0','61','0','100','0','0','0','0','0','20','1','0','0','0','0','0','1','0','0','0','0','0','0','0','Orc Scout - Between 0-5 Range - Start Auto Attack');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39068','0','10','11','9','0','100','0','5','15','0','0','21','0','0','0','0','0','0','1','0','0','0','0','0','0','0','Orc Scout - Between 5-15 Range - Disallow Combat Movement');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39068','0','11','0','61','0','100','0','0','0','0','0','20','0','0','0','0','0','0','1','0','0','0','0','0','0','0','Orc Scout - Between 5-15 Range - Stop Auto Attack');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('39068','0','12','0','7','0','100','1','0','0','0','0','40','1','0','0','0','0','0','1','0','0','0','0','0','0','0','Orc Scout - On Evade - Set Sheath Melee');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('40785','0','0','0','4','0','100','0','3000','3000','3000','3000','11','73485','2','0','0','0','0','2','0','0','0','0','0','0','0','gnomeregan machine gun  on aggro cast machine gun.');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('40785','0','2','0','4','0','100','0','1000','1000','1000','1000','21','0','0','0','0','0','0','1','0','0','0','0','0','0','0','gnomeregan machine gun  on aggro disable combat movement.( creature leaves its seat on vehicle to follow victim.)');
