UPDATE creature_template SET scriptname = 'boss_halion'WHERE entry ='39863';
UPDATE creature_template SET scriptname = 'npc_combustion_consumption'WHERE entry ='40001';
UPDATE creature_template SET scriptname = 'npc_meteor_strike_initial'WHERE entry ='40029';
UPDATE creature_template SET scriptname = 'npc_meteor_strike'WHERE entry ='40041';
UPDATE creature_template SET scriptname = 'npc_meteor_strike'WHERE entry ='40042';
UPDATE creature_template SET scriptname = 'npc_meteor_strike'WHERE entry ='40043';
UPDATE creature_template SET scriptname = 'npc_meteor_strike'WHERE entry ='40044';
UPDATE creature_template SET scriptname = 'npc_orb_carrier'WHERE entry ='40081';
UPDATE creature_template SET scriptname = 'npc_combustion_consumption'WHERE entry ='40135';
UPDATE creature_template SET scriptname = 'boss_twilight_halion'WHERE entry ='40142';
UPDATE creature_template SET scriptname = 'npc_halion_controller'WHERE entry ='40146';
UPDATE creature_template SET scriptname = 'npc_living_inferno'WHERE entry ='40681';
UPDATE creature_template SET scriptname = 'npc_living_ember'WHERE entry ='40683';
UPDATE creature_template SET scriptname = 'npc_defiant_troll'WHERE entry ='34830';
UPDATE creature_template SET scriptname = 'boss_zanzil'WHERE entry ='52053';
UPDATE creature_template SET scriptname = 'boss_kilnara'WHERE entry ='52059';
UPDATE creature_template SET scriptname = 'boss_jindo_the_godbreaker'WHERE entry ='52148';
REPLACE INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES('229','0','instance_blackrock_spire','0');
REPLACE INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES('269','1','instance_dark_portal','1');
REPLACE INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES('600','571','instance_drak_tharon','1');
REPLACE INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES('624','571','instance_archavon','0');
REPLACE INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES('671','0','instance_bastion_of_twilight','1');
REPLACE INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES('725','0','instance_stonecore','1');
REPLACE INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES('938','0','instance_end_time','1');
REPLACE INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES('940','0','instance_stonecore','1');
REPLACE INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES('229','0','instance_blackrock_spire','0');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('-52284','spell_dk_will_of_the_necropolis');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('-50391','spell_dk_improved_unholy_presence');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('-50365','spell_dk_improved_blood_presence');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('116','spell_mage_frostbolt');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('1535','spell_sha_fire_nova');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('2825','spell_sha_bloodlust');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('6474','spell_sha_earthbind_totem');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('32182','spell_sha_heroism');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('51490','spell_sha_thunderstorm');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('52041','spell_sha_healing_stream_totem');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('52759','spell_sha_ancestral_awakening_proc');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('59566','spell_sha_earthen_power');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('61698','spell_gen_ds_flush_knockback');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('62791','spell_xt002_heart_overload_periodic');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('74562','spell_halion_fiery_combustion');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('74567','spell_halion_mark_of_combustion');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('74610','spell_halion_damage_aoe_summon');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('74641','spell_halion_meteor_strike_marker');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('74769','spell_halion_twilight_cutter');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('74792','spell_halion_soul_consumption');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('74795','spell_halion_mark_of_consumption');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('74800','spell_halion_damage_aoe_summon');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('74807','spell_halion_enter_twilight_realm');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('74808','spell_halion_twilight_phasing');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('74812','spell_halion_leave_twilight_realm');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('75396','spell_halion_clear_debuffs');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('77844','spell_halion_twilight_cutter');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('77845','spell_halion_twilight_cutter');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('77846','spell_halion_twilight_cutter');
REPLACE INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES('123456','spell_halion_summon_exit_portals');