
-- On retail Kranal Fiss pathes.feel free to alter the waypoint_data id.
DELETE FROM `creature` WHERE `guid`=138704 AND `id`=5907;
INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`) values('138704','5907','1','1','1','4543','0','265.171','-3037.09','97.0417','3.21141','500','0','0','328','0','2','0','0','0');
UPDATE `creature_addon` SET `path_id`=5907 WHERE `guid`=138704;
DELETE FROM `waypoint_data` WHERE `id`=5907;
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`, `move_flag`, `action`, `action_chance`, `wpguid`) values('5907','1','265.171','-3037.09','96.9498','0','0','0','0','100','0');
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`, `move_flag`, `action`, `action_chance`, `wpguid`) values('5907','2','265.171','-3037.09','96.9498','0','0','0','0','100','0');
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`, `move_flag`, `action`, `action_chance`, `wpguid`) values('5907','3','261.46','-3044.74','96.3536','0','0','0','0','100','0');
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`, `move_flag`, `action`, `action_chance`, `wpguid`) values('5907','4','264.083','-3053.75','97.1762','0','0','0','0','100','0');
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`, `move_flag`, `action`, `action_chance`, `wpguid`) values('5907','5','271.8','-3056.49','97.1166','0','0','0','0','100','0');
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`, `move_flag`, `action`, `action_chance`, `wpguid`) values('5907','6','271.8','-3056.49','97.1166','0','0','0','0','100','0');
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`, `move_flag`, `action`, `action_chance`, `wpguid`) values('5907','7','262.745','-3039.22','96.8634','0','0','0','0','100','0');
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`, `move_flag`, `action`, `action_chance`, `wpguid`) values('5907','8','265.171','-3037.09','96.9498','0','0','0','0','100','0');
 
--creature_text for balgor whipshank during the quest 29109, Mor'shan Caravan Pick-Up
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('52333','1','0','Everybody onboard! This caravan\'s leaving for the Mor\'shan Rampart!','14','0','100','0','0','0','say1','0');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('52333','2','0','How are you doing back there? Not too bumpy I hope.','12','0','100','0','0','0','say2','0');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('52333','3','0','Our enemies wouldn\'t dare attack us this close to the Crossroads. It\'s further out that we\'ll have to watch our backs.','12','0','100','0','0','0','say3','0');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('52333','4','0','My family has been running caravan routes in the Barrens since Orgrimmar was settled. We raise and train the kodo\'s ourselves. My Sister, Nagala is the best kodo breeder outside of Mulgore.','12','0','100','0','0','0','say4','0');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('52333','5','0','Bet you didn\'t know a kodo can eat it\'s own weight in grass each day. Sure is a lot to shovel when it comes out the other end.','12','0','100','0','0','0','say5','0');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('52333','6','0','Hope you don\'t mind, but we\'ll stop at Dreadmist Camp to pick up additional supplies and fresh mounts for the last leg of the journey.','12','0','100','0','0','0','say6','0');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('52333','7','0','Nagala will have her famous grilled zhevra chops waiting for us, no doubt. She says I need to cut back and eat more vegetables, but I don\'t think I\'ve gained that much weight....do you?','12','0','100','0','0','0','say7','0');
 
--quest 27923   https://cata-twinhead.twinstar.cz/?quest=27923
 
UPDATE `quest_template` SET `RequiredNpcOrGo1`=27124,`RequiredNpcOrGoCount1`=5 WHERE `id`=27923;
UPDATE `gameobject_template` SET `AIName`='SmartGameObjectAI' WHERE `entry`=206682;
--smart_action=33 does not work with gameobjects, must be a quest credit npc.
DELETE FROM `smart_scripts` WHERE `entryorguid`=206682;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('206682','1','0','1','8','0','100','1','88646','0','0','0','33','27124','0','0','0','0','0','7','0','0','0','0','0','0','0','Bale of Hay - On Spell Hit - Give credit for quest 27923');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('206682','1','1','0','61','0','100','1','0','0','0','0','41','2000','0','0','0','0','0','1','0','0','0','0','0','0','0','Bale of Hay - Despawn after 2 second');
--Conditions for spell  https://cata-twinhead.twinstar.cz/?spell=88646
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) values('13','0','88646','0','0','31','0','5','206682','0','0','0','0','','hay stack');
 
