delete from arkcore_string where entry=63;
insert into arkcore_string (entry, content_default) values (63,"Wrong parameter id: %u, does not exist");
delete from arkcore_string where entry=64;
insert into arkcore_string (entry, content_default) values (64,"Wrong parameter realmId: %d");
delete from arkcore_string where entry=65;
insert into arkcore_string (entry, content_default) values (65,"Account %u (%s) granted permissions:");
delete from arkcore_string where entry=80;
insert into arkcore_string (entry, content_default) values (80,"BattleGround victories in the last 7 days
Alliance: %d
Horde: %d");
delete from arkcore_string where entry=81;
insert into arkcore_string (entry, content_default) values (81,"BattleGround scores storing is disabled!");
delete from arkcore_string where entry=96;
insert into arkcore_string (entry, content_default) values (96,"The guild name '%s' is already taken");
delete from arkcore_string where entry=97;
insert into arkcore_string (entry, content_default) values (97,"Changed guild name '%s' to '%s'");
delete from arkcore_string where entry=98;
insert into arkcore_string (entry, content_default) values (98,"'%s' already exists as character name, choose another one");
delete from arkcore_string where entry=99;
insert into arkcore_string (entry, content_default) values (99,"Player '%s' forced rename to '%s'");
delete from arkcore_string where entry=167;
insert into arkcore_string (entry, content_default) values (167,"This name is reserved, choose another one");
delete from arkcore_string where entry=1177;
insert into arkcore_string (entry, content_default) values (1177,"Displaying Guild Details for %s (Id: %u)");
delete from arkcore_string where entry=1178;
insert into arkcore_string (entry, content_default) values (1178,"| Guild Master: %s (GUID: %u)");
delete from arkcore_string where entry=1179;
insert into arkcore_string (entry, content_default) values (1179,"| Guild Creation Date: %s");
delete from arkcore_string where entry=1180;
insert into arkcore_string (entry, content_default) values (1180,"| Guild Members: %u");
delete from arkcore_string where entry=1181;
insert into arkcore_string (entry, content_default) values (1181,"| Guild Bank: %u gold");
delete from arkcore_string where entry=1182;
insert into arkcore_string (entry, content_default) values (1182,"| Guild MOTD: %s");
delete from arkcore_string where entry=1183;
insert into arkcore_string (entry, content_default) values (1183,"| Guild Information: %s");
delete from arkcore_string where entry=2030;
insert into arkcore_string (entry, content_default) values (2030,"|cff00ff00Completed by|r:|cff00ccff %s|r");
delete from arkcore_string where entry=5039;
insert into arkcore_string (entry, content_default) values (5039,"Console");
delete from arkcore_string where entry=5040;
insert into arkcore_string (entry, content_default) values (5040,"Character");
delete from arkcore_string where entry=5041;
insert into arkcore_string (entry, content_default) values (5041,"Permanently");
delete from arkcore_string where entry=5042;
insert into arkcore_string (entry, content_default) values (5042,"You are outdoors");
delete from arkcore_string where entry=5043;
insert into arkcore_string (entry, content_default) values (5043,"You are indoors");
delete from arkcore_string where entry=5044;
insert into arkcore_string (entry, content_default) values (5044,"no VMAP available for area info");
delete from arkcore_string where entry=5045;
insert into arkcore_string (entry, content_default) values (5045,"Map: %d inst: %d perm: %s diff: %d canReset: %s TTR: %s");
delete from arkcore_string where entry=5046;
insert into arkcore_string (entry, content_default) values (5046,"Player binds: %d");
delete from arkcore_string where entry=5047;
insert into arkcore_string (entry, content_default) values (5047,"Group binds: %d");
delete from arkcore_string where entry=5048;
insert into arkcore_string (entry, content_default) values (5048,"Unbinding map: %d inst: %d perm: %s diff: %d canReset: %s TTR: %s");
delete from arkcore_string where entry=5049;
insert into arkcore_string (entry, content_default) values (5049,"Instances unbound: %d");
delete from arkcore_string where entry=5050;
insert into arkcore_string (entry, content_default) values (5050,"Instances loaded: %d");
delete from arkcore_string where entry=5051;
insert into arkcore_string (entry, content_default) values (5051,"Players in instances: %d");
delete from arkcore_string where entry=5052;
insert into arkcore_string (entry, content_default) values (5052,"Instance saves: %d");
delete from arkcore_string where entry=5053;
insert into arkcore_string (entry, content_default) values (5053,"Players bound: %d");
delete from arkcore_string where entry=5054;
insert into arkcore_string (entry, content_default) values (5054,"Groups bound: %d");
delete from arkcore_string where entry=5055;
insert into arkcore_string (entry, content_default) values (5055,"Map is not a dungeon.");
delete from arkcore_string where entry=5056;
insert into arkcore_string (entry, content_default) values (5056,"Map has no instance data.");
delete from arkcore_string where entry=5057;
insert into arkcore_string (entry, content_default) values (5057,"Boss id %i state is now set to %i.");
delete from arkcore_string where entry=5058;
insert into arkcore_string (entry, content_default) values (5058,"Boss id %i state is %i.");
delete from arkcore_string where entry=5059;
insert into arkcore_string (entry, content_default) values (5059,"Mutes for account: %s");
delete from arkcore_string where entry=5060;
insert into arkcore_string (entry, content_default) values (5060,"No mutes for account: %s");
delete from arkcore_string where entry=5061;
insert into arkcore_string (entry, content_default) values (5061,"Mute Date: %20s Mutetime: %10u mins. Reason: %s Set by: %s");
