

UPDATE locales_quest SET OfferRewardText_loc3="Es ist wahr, wir wurden überfallen. Ich wage es nicht, noch mehr Soldaten dort hinauszuschicken und sie auch noch zu verlieren. Ich brauche einen Freiwilligen. Jemanden, der bereit ist, sein Leben aufs Spiel zu setzen!" WHERE Id=28780;

UPDATE locales_quest SET OfferRewardText_loc3="Es ist wahr, wir wurden überfallen. Ich wage es nicht, noch mehr Soldaten dort hinauszuschicken und sie auch noch zu verlieren. Ich brauche einen Freiwilligen. Jemanden, der bereit ist, sein Leben aufs Spiel zu setzen!", QuestGiverTextWindow_loc3="Stellvertreter Willem befindet sich am Kommandozelt hinter der Abtei von Nordhain.", QuestGiverTargetName_loc3="Stellvertreter Willem" WHERE Id=28785;

UPDATE locales_quest SET OfferRewardText_loc3="Es ist wahr, wir wurden überfallen. Ich wage es nicht, noch mehr Soldaten dort hinauszuschicken und sie auch noch zu verlieren. Ich brauche einen Freiwilligen. Jemanden, der bereit ist, sein Leben aufs Spiel zu setzen!", QuestGiverTextWindow_loc3="Stellvertreter Willem befindet sich am Kommandozelt hinter der Abtei von Nordhain.", QuestGiverTargetName_loc3="Stellvertreter Willem" WHERE Id=28784;

UPDATE locales_quest SET OfferRewardText_loc3="Es ist wahr, wir wurden überfallen. Ich wage es nicht, noch mehr Soldaten dort hinauszuschicken und sie auch noch zu verlieren. Ich brauche einen Freiwilligen. Jemanden, der bereit ist, sein Leben aufs Spiel zu setzen!", QuestGiverTextWindow_loc3="Stellvertreter Willem befindet sich am Kommandozelt hinter der Abtei von Nordhain.", QuestGiverTargetName_loc3="Stellvertreter Willem" WHERE Id=28786;

UPDATE locales_quest SET OfferRewardText_loc3="Es ist wahr, wir wurden überfallen. Ich wage es nicht, noch mehr Soldaten dort hinauszuschicken und sie auch noch zu verlieren. Ich brauche einen Freiwilligen. Jemanden, der bereit ist, sein Leben aufs Spiel zu setzen!", QuestGiverTextWindow_loc3="Stellvertreter Willem befindet sich am Kommandozelt hinter der Abtei von Nordhain.", QuestGiverTargetName_loc3="Sergeant Willem" WHERE Id=28787;

UPDATE locales_quest SET Details_loc3="Während Ihr unterwegs wart um zu trainieren, habe ich eine dringliche Nachricht von Stellvertreter Willem erhalten. Wie sich herausstellt, haben die Schwarzfelsorcs, goblinische Auftragsmörder angeheuert. Sie haben unser Bataillion hinter der Abtei aus dem Hinterhalt angegriffen. Willem bat mich, ihm einen Helden zu schicken. Ihr müsst ihnen helfen, $N!$B$BFindet Stellvertreter Willem nördlich der Abtei am Kommandozelt. Geht!", OfferRewardText_loc3="Es ist wahr, wir wurden überfallen. Ich wage es nicht, noch mehr Soldaten dort hinauszuschicken und sie auch noch zu verlieren. Ich brauche einen Freiwilligen. Jemanden, der bereit ist, sein Leben aufs Spiel zu setzen!", QuestGiverTextWindow_loc3="Stellvertreter Willem befindet sich am Kommandozelt hinter der Abtei von Nordhain.", QuestGiverTargetName_loc3="Sergeant Willem" WHERE Id=28788;

UPDATE locales_quest SET OfferRewardText_loc3="Es ist wahr, wir wurden überfallen. Ich wage es nicht, noch mehr Soldaten dort hinauszuschicken und sie auch noch zu verlieren. Ich brauche einen Freiwilligen. Jemanden, der bereit ist, sein Leben aufs Spiel zu setzen!" WHERE Id=28789;

UPDATE locales_quest SET QuestGiverTextWindow_loc3="Soldat von Sturmwind", QuestGiverTargetName_loc3="Soldat von Sturmwind" WHERE Id=29082;

UPDATE quest_template SET QuestGiverTextWindow="Injured Stormwind Infantry", QuestGiverTargetName="Injured Stormwind Infantry" WHERE Id=29082;

UPDATE locales_quest SET OfferRewardText_loc3="Ich glaube, Ihr versteht nun, welche Macht dem Licht innewohnt. Das Licht spendet Hoffnung, $GBruder:Schwester;, und das Licht lässt die Finsternis schwinden! GESEGNET SEI DAS LICHT!", RequestItemsText_loc3="Rettet unsere Soldaten!", QuestGiverTextWindow_loc3="Soldat von Sturmwind", QuestGiverTargetName_loc3="Soldat von Sturmwind" WHERE Id=28806;

UPDATE locales_quest SET OfferRewardText_loc3="Ich glaube, Ihr versteht nun, welche Macht dem Licht innewohnt. Das Licht spendet Hoffnung, $GBruder:Schwester;, und das Licht lässt die Finsternis schwinden! GESEGNET SEI DAS LICHT!", RequestItemsText_loc3="Rettet unsere Soldaten!", CompletedText_loc3="Kehrt zu Bruder Paxton hinter der Abtei von Nordhain im Wald von Elwynn zurück.", ObjectiveText1_loc3="Verletzten Soldaten wiederbelebt", QuestGiverTextWindow_loc3="Soldat von Sturmwind", QuestGiverTargetName_loc3="Soldat von Sturmwind" WHERE Id=28808;

UPDATE locales_quest SET OfferRewardText_loc3="Ich glaube, Ihr versteht nun, welche Macht dem Licht innewohnt. Das Licht spendet Hoffnung, $GBruder:Schwester;, und das Licht lässt die Finsternis schwinden! GESEGNET SEI DAS LICHT!", RequestItemsText_loc3="Rettet unsere Soldaten!", CompletedText_loc3="Kehrt zu Bruder Paxton hinter der Abtei von Nordhain im Wald von Elwynn zurück.", ObjectiveText1_loc3="Verletzten Soldaten wiederbelebt", QuestGiverTextWindow_loc3="Soldat von Sturmwind", QuestGiverTargetName_loc3="Soldat von Sturmwind" WHERE Id=28809;

UPDATE locales_quest SET OfferRewardText_loc3="Ich glaube, Ihr versteht nun, welche Macht dem Licht innewohnt. Das Licht spendet Hoffnung, $GBruder:Schwester;, und das Licht lässt die Finsternis schwinden! GESEGNET SEI DAS LICHT!", RequestItemsText_loc3="Rettet unsere Soldaten!", CompletedText_loc3="Kehrt zu Bruder Paxton hinter der Abtei von Nordhain im Wald von Elwynn zurück.", ObjectiveText1_loc3="Verletzten Soldaten wiederbelebt", QuestGiverTextWindow_loc3="Soldat von Sturmwind", QuestGiverTargetName_loc3="Soldat von Sturmwind" WHERE Id=28810;

UPDATE locales_quest SET OfferRewardText_loc3="Ich glaube, Ihr versteht nun, welche Macht dem Licht innewohnt. Das Licht spendet Hoffnung, $GBruder:Schwester;, und das Licht lässt die Finsternis schwinden! GESEGNET SEI DAS LICHT!", RequestItemsText_loc3="Rettet unsere Soldaten!", CompletedText_loc3="Kehrt zu Bruder Paxton hinter der Abtei von Nordhain im Wald von Elwynn zurück.", ObjectiveText1_loc3="Verletzten Soldaten wiederbelebt", QuestGiverTextWindow_loc3="Soldat von Sturmwind", QuestGiverTargetName_loc3="Soldat von Sturmwind" WHERE Id=28811;

UPDATE locales_quest SET Details_loc3="Habt Ihr Euch schon zum Heiligen Licht bekannt, $GBruder:Schwester;? Durch das Heilige Licht werden wir errettet! Das Heilige Licht versetzt mich in die Lage, diese überaus fordernden Soldaten zu heilen! Und durch das Heilige Licht werdet Ihr in der Lage sein, hinaus ins Feld nach Norden zu gehen, und unsere gefallenen Brüder zu retten!$B$BTragt dieses Gebetsbuch mit Euch ins Feld und wirkt die heilende Berührung des Lichts auf die Verwundeten.", OfferRewardText_loc3="Ich glaube, Ihr versteht nun, welche Macht dem Licht innewohnt. Das Licht spendet Hoffnung, $GBruder:Schwester;, und das Licht lässt die Finsternis schwinden! GESEGNET SEI DAS LICHT!", RequestItemsText_loc3="Rettet unsere Soldaten!", CompletedText_loc3="Kehrt zu Bruder Paxton hinter der Abtei von Nordhain im Wald von Elwynn zurück.", ObjectiveText1_loc3="Verletzten Soldaten wiederbelebt", QuestGiverTextWindow_loc3="Soldat von Sturmwind", QuestGiverTargetName_loc3="Soldat von Sturmwind" WHERE Id=28812;

UPDATE locales_quest SET OfferRewardText_loc3="Ich glaube, Ihr versteht nun, welche Macht dem Licht innewohnt. Das Licht spendet Hoffnung, $GBruder:Schwester;, und das Licht lässt die Finsternis schwinden! GESEGNET SEI DAS LICHT!", RequestItemsText_loc3="Rettet unsere Soldaten!", CompletedText_loc3="Kehrt zu Bruder Paxton hinter der Abtei von Nordhain im Wald von Elwynn zurück.", QuestGiverTextWindow_loc3="Soldat von Sturmwind", QuestGiverTargetName_loc3="Soldat von Sturmwind" WHERE Id=28813;

UPDATE locales_quest SET OfferRewardText_loc3="Ihr habt diesen Monstern eine Lektion erteilt! Sie werden es sich zweimal überlegen, bevor sie noch einen Mordauftrag der Orcs annehmen.", RequestItemsText_loc3="Tötet die goblinischen Auftragsmörder!", CompletedText_loc3="Kehrt zu Unteroffizier Willem hinter der Abtei von Nordhain im Wald von Elwynn zurück." WHERE Id=28797;

UPDATE locales_quest SET OfferRewardText_loc3="Ihr habt diesen Monstern eine Lektion erteilt! Sie werden es sich zweimal überlegen, bevor sie noch einen Mordauftrag der Orcs annehmen.", RequestItemsText_loc3="Tötet die goblinischen Auftragsmörder!", CompletedText_loc3="Kehrt zu Unteroffizier Willem hinter der Abtei von Nordhain im Wald von Elwynn zurück.", QuestGiverTextWindow_loc3="Dies ist ein goblinischer Auftragsmörder. Fieses kleines Monster!", QuestGiverTargetName_loc3="Goblinischer Auftragsmörder" WHERE Id=28796;

UPDATE locales_quest SET OfferRewardText_loc3="Ihr habt diesen Monstern eine Lektion erteilt! Sie werden es sich zweimal überlegen, bevor sie noch einen Mordauftrag der Orcs annehmen.", RequestItemsText_loc3="Tötet die goblinischen Auftragsmörder!", CompletedText_loc3="Kehrt zu Unteroffizier Willem hinter der Abtei von Nordhain im Wald von Elwynn zurück.", QuestGiverTextWindow_loc3="Dies ist ein goblinischer Auftragsmörder. Fieses kleines Monster!", QuestGiverTargetName_loc3="Goblinischer Auftragsmörder" WHERE Id=28795;

UPDATE locales_quest SET OfferRewardText_loc3="Ihr habt diesen Monstern eine Lektion erteilt! Sie werden es sich zweimal überlegen, bevor sie noch einen Mordauftrag der Orcs annehmen.", RequestItemsText_loc3="Tötet die goblinischen Auftragsmörder!", CompletedText_loc3="Kehrt zu Unteroffizier Willem hinter der Abtei von Nordhain im Wald von Elwynn zurück.", QuestGiverTextWindow_loc3="Dies ist ein goblinischer Auftragsmörder. Fieses kleines Monster!", QuestGiverTargetName_loc3="Goblinischer Auftragsmörder" WHERE Id=28794;

UPDATE locales_quest SET OfferRewardText_loc3="Ihr habt diesen Monstern eine Lektion erteilt! Sie werden es sich zweimal überlegen, bevor sie noch einen Mordauftrag der Orcs annehmen.", RequestItemsText_loc3="Tötet die goblinischen Auftragsmörder!", CompletedText_loc3="Kehrt zu Unteroffizier Willem hinter der Abtei von Nordhain im Wald von Elwynn zurück.", QuestGiverTextWindow_loc3="Dies ist ein goblinischer Auftragsmörder. Fieses kleines Monster!", QuestGiverTargetName_loc3="Goblinischer Auftragsmörder" WHERE Id=28793;

UPDATE locales_quest SET OfferRewardText_loc3="Ihr habt diesen Monstern eine Lektion erteilt! Sie werden es sich zweimal überlegen, bevor sie noch einen Mordauftrag der Orcs annehmen.", RequestItemsText_loc3="Tötet die goblinischen Auftragsmörder!", CompletedText_loc3="Kehrt zu Unteroffizier Willem hinter der Abtei von Nordhain im Wald von Elwynn zurück.", QuestGiverTextWindow_loc3="Dies ist ein goblinischer Auftragsmörder. Fieses kleines Monster!", QuestGiverTargetName_loc3="Goblinischer Auftragsmörder" WHERE Id=28792;

UPDATE locales_quest SET OfferRewardText_loc3="Ihr habt diesen Monstern eine Lektion erteilt! Sie werden es sich zweimal überlegen, bevor sie noch einen Mordauftrag der Orcs annehmen.", RequestItemsText_loc3="Tötet die goblinischen Auftragsmörder!" WHERE Id=28791;

UPDATE locales_quest SET OfferRewardText_loc3="Dank Eurer Hilfe ist es uns gelungen, die nördlichen und westlichen Abschnitte von Nordhain zu sichern. Dennoch gibt es im Osten noch immer eine ziemlich große Ansammlung von Schwarzfeslorcs und sie haben damit begonnen, den Wald niederzubrennen!" WHERE Id=28817;

UPDATE locales_quest SET OfferRewardText_loc3="Dank Eurer Hilfe ist es uns gelungen, die nördlichen und westlichen Abschnitte von Nordhain zu sichern. Dennoch gibt es im Osten noch immer eine ziemlich große Ansammlung von Schwarzfeslorcs und sie haben damit begonnen, den Wald niederzubrennen!" WHERE Id=28818;

UPDATE locales_quest SET OfferRewardText_loc3="Dank Eurer Hilfe ist es uns gelungen, die nördlichen und westlichen Abschnitte von Nordhain zu sichern. Dennoch gibt es im Osten noch immer eine ziemlich große Ansammlung von Schwarzfeslorcs und sie haben damit begonnen, den Wald niederzubrennen!" WHERE Id=28819;

UPDATE locales_quest SET OfferRewardText_loc3="Dank Eurer Hilfe ist es uns gelungen, die nördlichen und westlichen Abschnitte von Nordhain zu sichern. Dennoch gibt es im Osten noch immer eine ziemlich große Ansammlung von Schwarzfeslorcs und sie haben damit begonnen, den Wald niederzubrennen!" WHERE Id=28820;

UPDATE locales_quest SET OfferRewardText_loc3="Dank Eurer Hilfe ist es uns gelungen, die nördlichen und westlichen Abschnitte von Nordhain zu sichern. Dennoch gibt es im Osten noch immer eine ziemlich große Ansammlung von Schwarzfeslorcs und sie haben damit begonnen, den Wald niederzubrennen!" WHERE Id=28821;

UPDATE locales_quest SET Details_loc3="Ausgezeichnete Arbeit, $N! Sie werden uns definitiv nicht mehr in den Rücken fallen. Wir kümmern uns um die Nachzügler. Ich will, dass Ihr zurück zu Marschall McBride geht, der südlich von hier vor der Abtei von Nordhain steht. Lasst ihn wissen, dass die Situation mit den Goblins unter Kontrolle ist.$B$BLebt wohl, $C.", OfferRewardText_loc3="Dank Eurer Hilfe ist es uns gelungen, die nördlichen und westlichen Abschnitte von Nordhain zu sichern. Dennoch gibt es im Osten noch immer eine ziemlich große Ansammlung von Schwarzfeslorcs und sie haben damit begonnen, den Wald niederzubrennen!" WHERE Id=28822;

UPDATE locales_quest SET OfferRewardText_loc3="Dank Eurer Hilfe ist es uns gelungen, die nördlichen und westlichen Abschnitte von Nordhain zu sichern. Dennoch gibt es im Osten noch immer eine ziemlich große Ansammlung von Schwarzfeslorcs und sie haben damit begonnen, den Wald niederzubrennen!" WHERE Id=28823;





