

UPDATE `quest_template` SET `QuestGiverPortrait` =26091 WHERE `Id` =26591;
UPDATE `creature_template` SET `modelid1` =26091, `modelid2` =0 WHERE `entry` =43229;

delete from `creature_text` where `entry`=43229;
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('43229','0','1','I think I can make it back on my own.','12','0','100','0','0','0',NULL,'43414');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('43229','0','2','You\'re a strange-looking creature. Thank you.','12','0','100','0','0','0',NULL,'43415');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('43229','0','3','What happened?','12','0','100','0','0','0',NULL,'43416');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('43229','0','4','Kill a few for me, would you?','12','0','100','0','0','0',NULL,'43417');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('43229','0','5','Don\'t worry about me. We have to rescue the king!','12','0','100','0','0','0',NULL,'43418');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('43229','0','6','You need to kill Troggzor the Earthinator!','12','0','100','0','0','0',NULL,'43420');

delete from `smart_scripts` where `entryorguid`=43229 and `source_type`=0;
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('43229','0','0','0','8','0','100','1','80987','0','0','0','33','43229','0','0','0','0','0','7','0','0','0','0','0','0','0','Give Kill Monster Credit on Quest item Heal');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('43229','0','1','0','8','0','100','0','80987','0','0','0','1','0','2000','0','0','0','0','1','0','0','0','0','0','0','0','Injured Earthen - OnSpellhit - Random Talk.');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('43229','0','2','3','8','0','100','0','80987','0','0','0','28','81238','0','0','0','0','0','1','0','0','0','0','0','0','0','Injured Earthen - OnSpellhit - Remove death aura..');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('43229','0','3','4','61','0','100','0','0','0','0','0','46','20','0','0','0','0','0','1','0','0','0','0','0','0','0','Injured Earthen - OnSmartLink - Flee.');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('43229','0','4','0','61','0','100','0','0','0','0','0','41','2000','0','0','0','0','0','1','0','0','0','0','0','0','0','Injured Earthen - OnSmartLink - Despawn 2 secs.');
