
-- not forget: set you own password!!!!!!
 
GRANT USAGE ON *.* TO 'arkania'@'localhost' IDENTIFIED BY 'SetYouOwnPasswordHere' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 ;
GRANT USAGE ON *.* TO 'arkania'@'127.0.0.1' IDENTIFIED BY 'SetYouOwnPasswordHere' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 ;
GRANT USAGE ON *.* TO 'arkania'@'%' IDENTIFIED BY 'SetYouOwnPasswordHere' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 ;
